
name: Build database

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-database:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install system requirements
        run: sudo apt-get install gdal-bin libgdal-dev libsqlite3-mod-spatialite spatialite-bin
      - name: install python requirements
        run: |-
          pip install .
          pip install -r requirements.txt
      - name: build
        run: make
